### ISSUE TITLE
Free trial cannot use in github actions 

### ISSUE THREAD

**Issue by eunhwa-park** [fortify/gha-setup-fod-uploader#4]
I'm using a FoD free trial in 15days but I cannot use gha-setup-fod-uploader in github actions.

And I received the below answer from micro focus.
"Please be advised that currently, the FoD Trial Environment does not support integration of source control."

Is it possible to test this in github actions using free trial?

This is an error log in github actions.
==================================
Run java -jar $FOD_UPLOAD_JAR -z package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
Authenticating
java.io.IOException: Unexpected code Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://api.ams.fortify.com//oauth/token}
	at com.fortify.fod.fodapi.FodApi.authenticate(FodApi.java:98)
	at com.fortify.fod.Main.main(Main.java:110)
Beginning upload
java.lang.NullPointerException
	at com.fortify.fod.fodapi.models.GenericErrorResponse.toString(GenericErrorResponse.java:15)
	at com.fortify.fod.fodapi.controllers.StaticScanController.StartStaticScan(StaticScanController.java:123)
	at com.fortify.fod.Main.main(Main.java:115)
Retiring Token : Token has already expired
Aug 24, 2021 8:27:03 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://api.ams.fortify.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Error: Process completed with exit code 1.
==================================

**Comment by rsenden** [comment]
It should be possible to use this action and FoDUploader with the FoD free trial, however please note the following:

* The API URL for trials is https://api.trial.fortify.com; according to the output you shared you are using https://api.ams.fortify.com/ which is not valid for trials
* For API authentication you will need to use either an API token or Personal Access Token; username/password authentication is not supported for API authentication in the trial environment

Also note that the trial environment only allows for single assessments (not subscriptions). You can use this GitHub Action and FoDUploader for test or demo purposes in an FoD trial environment, but in real-world scenarios you would usually want to use subscription scans when integrating FoD scans into GitHub Action workflows.
